sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/gcloud/
before_install:
- openssl aes-256-cbc -K $encrypted_8475bbc8dba7_key -iv $encrypted_8475bbc8dba7_iv
  -in paxportcloud-travis-ci.json.enc -out paxportcloud-travis-ci.json -d
- if [ ! -d $HOME/google-cloud-sdk ]; then curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-135.0.0-linux-x86_64.tar.gz
  -o gcloudsdk.tar.gz; tar -xvzf gcloudsdk.tar.gz; ./google-cloud-sdk/install.sh --quiet;
  fi
- ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file paxportcloud-travis-ci.json
